name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false # 로컬 환경 시 fail-fast false.
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle  

      # # Config 서버 URL을 환경 변수로 설정
      # - name: Set Config Server URL as environment variable
      #   run: |
      #     echo "CONFIG_SERVER_URL=${{ secrets.CONFIG_SERVER_URL }}" >> $GITHUB_ENV

      # # Config 서버 URL이 비어 있지 않으면 실행
      # - name: Set environment variable for Config Server URL
      #   if: ${{ env.CONFIG_SERVER_URL != '' }}
      #   run: |
      #     echo "SPRING_CLOUD_CONFIG_URI=${{ env.CONFIG_SERVER_URL }}" >> $GITHUB_ENV
      
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
      
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      
      - name: Build, unit tests and integration tests
        working-directory: catalog-service
        run: |
          chmod +x gradlew
          ./gradlew build
